server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        default_type application/json; # Ensures the browser reads files as JSON
        add_header Access-Control-Allow-Origin *; # Allows your frontend to fetch this JSON
    }
}
